const tech = [
    "TypeScript",
    "JavaScript",
    "Python",
    "Elixir",
    "Java",
    "C#",
    "C",
    "C++",
    "Swift",
    "bash | unix",
    "Node.js",
    "React Native",
    "React",
    "Next.js",
    "Styled Components",
    "p5.js",
    "Chrome/Firefox Extensions",
    "Electron.js",
    "Unity",
    ".NET Core",
    "CSS | SASS",
    "AWS",
    "Lambda",
    "Firebase",
    "SQL",
    "MongoDB",
    "socket.io",
    "npm",
    "yarn workspaces",
    "monorepo",
    "Docker",
    "Jupyter",
    "Keras",
    "gtk",
    "Google Cloud",
    "Spark",
]

console.log(this)
const content = tech.map(t => `<span>${t}</span>`).join(' ')
document.querySelector(".marquee").innerHTML = `<p>${content}</p><p>${content}</p>`